version: '3'

services:
  web:
    image: nodejs-angular-starter
    build:
      context: .
      args:
        - NODE_ENV
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - '~/dockers_data/web/logs:/logs'

volumes:
  
